import "dotenv/config";
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { db } from "./index";
import {
  artisans,
  inquiries,
  properties,
  submissions,
  type NewArtisan,
  type NewProperty,
  type NewSubmission,
} from "./schema";

/** Minimal valid one-page PDF with a title line — placeholder documents. */
function pdfBytes(title: string): Buffer {
  const esc = title.replace(/([()\\])/g, "\\$1");
  const content = `BT /F1 13 Tf 64 740 Td (QuashNarh Real Estate - Document Copy) Tj ET BT /F1 10 Tf 64 716 Td (${esc}) Tj ET`;
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((o, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((off) => {
    pdf += `${String(off).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, "latin1");
}

const DOC_LABELS: Record<string, string> = {
  title: "Land Title Certificate / Indenture",
  sitePlan: "Site Plan",
  idCard: "Owner's Ghana Card (scan)",
  taxReceipt: "Current Property Tax Receipt",
  permit: "Building Permit",
};

/** Writes placeholder PDFs for a seeded submission and returns their URLs. */
async function seedDocuments(n: number, owner: string): Promise<NewSubmission["documents"]> {
  const dir = path.join(process.cwd(), "uploads");
  await mkdir(dir, { recursive: true });
  const docs: { type: string; label: string; path: string }[] = [];
  for (const type of ["title", "sitePlan", "idCard", "taxReceipt"] as const) {
    const filename = `sub-seed-${n}-${type}.pdf`;
    await writeFile(path.join(dir, filename), pdfBytes(`${DOC_LABELS[type]} - ${owner}`));
    docs.push({ type, label: DOC_LABELS[type], path: `/uploads/${filename}` });
  }
  return docs;
}

const px = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.${
    id === 5517853 ? "png" : "jpeg"
  }?auto=compress&cs=tinysrgb&fit=crop&h=1067&w=1600`;

/** Passport-frame crop (≈ 35 × 45 mm ratio). */
const pxFace = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=694&w=540`;

const AGENTS = {
  ama: {
    agentName: "Ama Serwaa Boateng",
    agentPhone: "+233 24 455 0147",
    agentEmail: "ama@quashnarh.com",
  },
  kofi: {
    agentName: "Kofi Ansah",
    agentPhone: "+233 20 812 0156",
    agentEmail: "kofi@quashnarh.com",
  },
  efua: {
    agentName: "Efua Addo",
    agentPhone: "+233 55 304 0193",
    agentEmail: "efua@quashnarh.com",
  },
  nanaYaw: {
    agentName: "Nana Yaw Frimpong",
    agentPhone: "+233 26 771 0118",
    agentEmail: "nanayaw@quashnarh.com",
  },
};

const data: NewProperty[] = [
  {
    slug: "baobab-pavilion-east-legon",
    title: "The Baobab Pavilion",
    description:
      "A study in transparency and light, The Baobab Pavilion rises above East Legon's canopy with walls of frameless glass that dissolve the boundary between interior and sky. Conceived by an award-winning Accra studio, the residence unfolds across a single cinematic level — terrazzo floors cooled by cross-ventilation, a cantilevered great room, and a kitchen carved from a single slab of marble.\n\nOutdoors, a 60-foot infinity edge pool mirrors the garden's mature baobab, flanked by frangipani and flame trees. The primary suite occupies its own wing with a spa-grade bath in book-matched onyx, while four guest suites and detached staff quarters ensure privacy for all. This is architecture as art, ten minutes from Airport City.",
    listingType: "sale",
    propertyType: "villa",
    price: 4850000,
    bedrooms: 5,
    bathrooms: 6,
    areaSqft: 6240,
    lotSqft: 14800,
    yearBuilt: 2019,
    address: "12 Baobab Close, East Legon Hills",
    city: "East Legon",
    state: "Greater Accra",
    zip: "GA-448-7165",
    images: [px(8134821), px(8135492), px(7031879), px(8135118)],
    features: [
      "60-ft infinity edge pool",
      "Floor-to-ceiling glass walls",
      "Marble chef's kitchen",
      "Home cinema room",
      "Detached staff quarters",
      "Standby generator + inverter",
      "Smart home automation",
      "4-car gallery garage",
      "Landscaped baobab garden",
      "10 min to Airport City",
    ],
    status: "available",
    featured: true,
    ...AGENTS.ama,
  },
  {
    slug: "palm-grove-estate-east-airport",
    title: "Palm Grove Estate",
    description:
      "Set behind Royal Palm Avenue on a manicured half-acre, Palm Grove Estate reimagines the family compound with contemporary Ghanaian warmth. A deep shaded veranda gives way to sun-drenched interiors — porcelain floors, hardwood accents, and louvre windows that pull the evening breeze through every room.\n\nThe heart of the home is a double-height great room anchored by a stone feature wall, flowing into a chef's kitchen with a 12-foot island. The main-level primary suite opens to a private patio, and the backyard delivers a pool, covered summer kitchen, and room to roam. Zoned minutes from Ghana International School.",
    listingType: "sale",
    propertyType: "house",
    price: 1285000,
    bedrooms: 4,
    bathrooms: 3,
    areaSqft: 2980,
    lotSqft: 21780,
    yearBuilt: 2021,
    address: "47 Royal Palm Avenue",
    city: "East Airport",
    state: "Greater Accra",
    zip: "GA-091-5522",
    images: [px(5517853), px(7167073), px(7214450), px(8135505)],
    features: [
      "Swimming pool & deck",
      "Deep shaded veranda",
      "12-ft kitchen island",
      "Stone feature wall",
      "Covered summer kitchen",
      "Main-level primary suite",
      "3-car garage",
      "Borehole + water storage",
      "Walk-in pantry",
      "Near Ghana Int'l School",
    ],
    status: "available",
    featured: false,
    ...AGENTS.kofi,
  },
  {
    slug: "osu-sky-penthouse",
    title: "Osu Sky Penthouse",
    description:
      "Perched above Oxford Street's hum, the Osu Sky Penthouse commands a 360-degree panorama from the Gulf of Guinea to the city skyline. A private elevator vestibule opens to a 62-foot great room wrapped in floor-to-ceiling glass, where Atlantic sunsets perform nightly over Jamestown's lighthouse.\n\nInteriors by a celebrated London-Accra studio pair smoked oak with honed basalt and brass. The corner primary suite floats above the city with a dressing gallery and marble spa bath. Residents enjoy a full floor of amenities — lap pool, private dining room, fitness pavilion, and a landscaped observatory terrace.",
    listingType: "sale",
    propertyType: "penthouse",
    price: 8900000,
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 4120,
    lotSqft: null,
    yearBuilt: 2016,
    address: "1 Independence Avenue, PH1",
    city: "Osu",
    state: "Greater Accra",
    zip: "GA-027-4418",
    images: [px(33234792), px(8135496), px(7167061), px(8135529)],
    features: [
      "Private elevator entry",
      "360° ocean & city views",
      "62-ft great room",
      "Corner primary suite",
      "Residents' lap pool & spa",
      "Private dining room",
      "Observatory terrace",
      "24-hour concierge",
      "Climate-controlled wine storage",
      "Full standby power",
    ],
    status: "available",
    featured: true,
    ...AGENTS.efua,
  },
  {
    slug: "republic-loft-osu",
    title: "The Republic Loft",
    description:
      "In the heart of Osu's creative corridor, The Republic Loft pairs gallery bones with a collector's finish. Eleven-foot ceilings, polished concrete, and oversized arched windows flood the open plan with northern light — a canvas equally suited to living, working, and entertaining.\n\nThe renovated kitchen features custom odum cabinetry and imported appliances, while both bedrooms offer en-suite baths and built-ins. A deeded storage room and secure parking complete the offering, two blocks from Oxford Street and five minutes to Labadi Beach.",
    listingType: "rent",
    propertyType: "loft",
    price: 4850,
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1240,
    lotSqft: null,
    yearBuilt: 2011,
    address: "18 Fourth Circular Road, 4B",
    city: "Osu",
    state: "Greater Accra",
    zip: "GA-015-8890",
    images: [px(27459248), px(8082242), px(7533852), px(28853343)],
    features: [
      "11-ft ceilings",
      "Oversized arched windows",
      "In-unit washer/dryer",
      "Custom odum-wood kitchen",
      "Two en-suite baths",
      "Deeded storage room",
      "Secure parking",
      "Pet friendly",
      "Backup power & water",
      "5 min to Labadi Beach",
    ],
    status: "available",
    featured: false,
    ...AGENTS.efua,
  },
  {
    slug: "aburi-modern",
    title: "Aburi Modern",
    description:
      "A love letter to mountain modernism, Aburi Modern rests on the Akuapem ridge where the city haze gives way to cool highland air. The post-and-beam architecture opens completely via pocketing glass walls, doubling the living space onto a stone terrace with infinity pool facing the valley.\n\nThe interiors honor clean tropical lines — polished concrete, iroko screens, and a floating hearth — while systems are thoroughly modern: solar array with battery storage, borehole, zoned cooling, and Starlink-ready connectivity. Four en-suite bedrooms wrap a shaded courtyard of tree ferns and orchids, minutes from Aburi Botanical Gardens.",
    listingType: "sale",
    propertyType: "house",
    price: 2395000,
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3480,
    lotSqft: 15000,
    yearBuilt: 2022,
    address: "9 Ridge Road, Akuapem",
    city: "Aburi",
    state: "Eastern Region",
    zip: "EO-113-7782",
    images: [px(8082328), px(7546323), px(7166645), px(8135105)],
    features: [
      "Infinity pool over the valley",
      "Pocketing glass walls",
      "Solar array + battery",
      "Iroko screens & concrete",
      "Floating hearth",
      "Four en-suite bedrooms",
      "Fern & orchid courtyard",
      "Starlink-ready",
      "Outdoor fire pit lounge",
      "5 min to Botanical Gardens",
    ],
    status: "available",
    featured: true,
    ...AGENTS.ama,
  },
  {
    slug: "marina-view-residence-tema",
    title: "Marina View Residence",
    description:
      "High above Community 25's marina, this corner residence frames fishing boats, container cranes on the horizon, and the lagoon through walls of glass. The open living plan flows to a covered terrace large enough for dining eight, made year-round with ceiling fans and glass railings.\n\nMarina View's amenities rival boutique hotels: 24-hour security, rooftop lounge, two guest suites, and a fitness center. The motorway interchange is three minutes away; the port's business district is your daily view.",
    listingType: "rent",
    propertyType: "condo",
    price: 3650,
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1180,
    lotSqft: null,
    yearBuilt: 2018,
    address: "Block B, Harbour Road, Community 25",
    city: "Tema",
    state: "Greater Accra",
    zip: "GT-204-6613",
    images: [px(37224965), px(6297086), px(7005291), px(6585757)],
    features: [
      "Corner unit with lagoon views",
      "Covered terrace",
      "24-hour security",
      "Rooftop lounge",
      "Fitness center",
      "Two guest suites",
      "In-unit laundry",
      "Parking & storage included",
      "3 min to motorway",
      "Pet friendly",
    ],
    status: "available",
    featured: false,
    ...AGENTS.nanaYaw,
  },
  {
    slug: "courtyard-house-cantonments",
    title: "The Courtyard House",
    description:
      "Organized around a serene open-air courtyard, this Cantonments contemporary turns diplomatic-quarter living inward to light and sky. Every principal room borrows views of the central garden — a sculptural frangipani, a rill water feature, and a floating steel staircase that doubles as art.\n\nThe great room's 16-foot ceilings are lined in rift-sawn oak; the kitchen hides behind flush walnut panels with imported appliances. Outdoor rooms extend the footprint with a negative-edge pool, shaded lounge, and garden court, all walking distance to the US Embassy row and Labone's cafés.",
    listingType: "sale",
    propertyType: "house",
    price: 1875000,
    bedrooms: 4,
    bathrooms: 3,
    areaSqft: 3050,
    lotSqft: 12500,
    yearBuilt: 2008,
    address: "6 Sir Charles Arden-Clarke Close",
    city: "Cantonments",
    state: "Greater Accra",
    zip: "GA-036-2294",
    images: [px(7031604), px(8089172), px(8082197), px(6394612)],
    features: [
      "Open-air central courtyard",
      "Negative-edge pool",
      "Imported appliance suite",
      "16-ft oak-lined ceilings",
      "Shaded pool lounge",
      "Garden court",
      "Diplomatic quarter location",
      "Solar water heating",
      "3-car garage",
      "Staff quarters",
    ],
    status: "available",
    featured: false,
    ...AGENTS.kofi,
  },
  {
    slug: "mango-cottage-aburi",
    title: "Mango Cottage",
    description:
      "Down a hibiscus-lined lane minutes from Aburi town, Mango Cottage is the highland weekender distilled — valley views from every window and a broad veranda made for long evenings. The renovated interior layers reclaimed teak, handmade tile, and a proper cook's kitchen.\n\nThe acre-plus grounds include mature mango and avocado trees, raised kitchen gardens, a fire circle shaded by silk cotton, and a permitted guest studio above the detached garage. Offered furnished, it's a turnkey slice of Akuapem life.",
    listingType: "sale",
    propertyType: "cottage",
    price: 985000,
    bedrooms: 3,
    bathrooms: 2,
    areaSqft: 1760,
    lotSqft: 47916,
    yearBuilt: 1998,
    address: "13 Botanical Lane, Akuapem",
    city: "Aburi",
    state: "Eastern Region",
    zip: "EO-107-3315",
    images: [px(5997993), px(6980661), px(6587896), px(7546276)],
    features: [
      "Valley & forest views",
      "Mango & avocado orchard",
      "Permitted guest studio",
      "Reclaimed teak floors",
      "Fire circle",
      "Raised kitchen gardens",
      "Broad covered veranda",
      "Outdoor shower",
      "Offered furnished",
      "Cool highland climate",
    ],
    status: "available",
    featured: false,
    ...AGENTS.ama,
  },
  {
    slug: "skyline-on-independence-accra",
    title: "Skyline on Independence",
    description:
      "On the 14th floor of an Airport City landmark, this corner two-bedroom puts the capital on permanent display — the Independence Arch, the sea haze beyond, and the city's evening lights. Interiors were refreshed in 2025 with wide-plank floors, quartz counters, and motorized shades.\n\nThe full-amenity building offers a sundeck pool, residents' kitchen, work-from-home lounges, and a fitness center. Steps to Marina Mall, the Airport, and the business district's towers.",
    listingType: "rent",
    propertyType: "apartment",
    price: 2940,
    bedrooms: 2,
    bathrooms: 1,
    areaSqft: 1050,
    lotSqft: null,
    yearBuilt: 2020,
    address: "Tower 2, Liberation Road, 1406",
    city: "Airport City",
    state: "Greater Accra",
    zip: "GA-201-0946",
    images: [px(24259313), px(8082243), px(7214450), px(28853343)],
    features: [
      "Corner skyline views",
      "Renovated 2025",
      "Sundeck pool",
      "Co-working lounges",
      "Fitness center",
      "Residents' kitchen",
      "In-unit laundry",
      "Secure parking available",
      "Steps to Marina Mall",
      "Pet friendly",
    ],
    status: "available",
    featured: false,
    ...AGENTS.nanaYaw,
  },
  {
    slug: "dune-villa-ada",
    title: "The Dune Villa",
    description:
      "Behind gates on Ada Foah's coveted sand bar, The Dune Villa is a sculpted concrete-and-glass retreat with 60 feet of estuary frontage where the Volta meets the Atlantic. Inside, a triple-height atrium carries the sound of surf through gallery-white walls; outside, dunes of native grasses dissolve into the beach.\n\nThe main level opens to a teak deck with infinity spa suspended over the sand; above, the primary suite commands a private terrace with outdoor fireplace. A lower level houses a cinema, gym, and beach room with outdoor shower. This is the Volta estuary at its most private.",
    listingType: "sale",
    propertyType: "villa",
    price: 7200000,
    bedrooms: 6,
    bathrooms: 7,
    areaSqft: 7800,
    lotSqft: 18200,
    yearBuilt: 2023,
    address: "Plot 22, Estuary Road, Ada Foah",
    city: "Ada",
    state: "Greater Accra",
    zip: "GD-101-7884",
    images: [px(31817157), px(7174113), px(7166645), px(8135105)],
    features: [
      "60 ft of estuary frontage",
      "Gated private drive",
      "Infinity spa over the beach",
      "Private cinema",
      "Gym & beach room",
      "Triple-height atrium",
      "Teak oceanfront deck",
      "Outdoor fireplace terrace",
      "Chef's + catering kitchen",
      "Full solar + generator backup",
    ],
    status: "available",
    featured: true,
    ...AGENTS.ama,
  },
  {
    slug: "jamestown-heritage-townhouse",
    title: "Jamestown Heritage Townhouse",
    description:
      "A rare 1925 masonry townhouse where Old Accra's history meets magazine-ready renovation. Original timber floors and 12-foot ceilings meet a marble kitchen and a courtyard garden lush with jasmine and bougainvillea, a short climb from the lighthouse.\n\nThree en-suite bedrooms span two quiet floors above; below, French doors open the parlor level to a 40-foot loggia for alfresco dining. Off-street parking for two and a whole-home generator complete an offering for the connoisseur of Old Accra.",
    listingType: "rent",
    propertyType: "townhouse",
    price: 3450,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 2120,
    lotSqft: 3050,
    yearBuilt: 1925,
    address: "14 Lighthouse Road, Jamestown",
    city: "Jamestown",
    state: "Greater Accra",
    zip: "GA-144-5027",
    images: [px(7587470), px(7546323), px(6587896), px(8135505)],
    features: [
      "Historic 1925 architecture",
      "12-ft ceilings",
      "Original timber floors",
      "Marble kitchen",
      "Private jasmine courtyard",
      "40-ft covered loggia",
      "Three en-suite bedrooms",
      "Off-street parking (2)",
      "Whole-home generator",
      "3 min to lighthouse",
    ],
    status: "pending",
    featured: false,
    ...AGENTS.efua,
  },
  {
    slug: "shai-hills-ranch",
    title: "Shai Hills Ranch",
    description:
      "Where the Shai Hills reserve rises over the plains, this ranch spreads a single story of timber and glass across five acacia-shaded acres. Walls of glass frame baboons' granite kopjes and savanna sunsets; a stone hearth anchors a vaulted great room built for gathering.\n\nThe 2024 renovation added a chef's kitchen, spa-level primary wing, and a 1,200 sq ft powered barn with workshop and loft — ready for horses, hobbies, or the ultimate gear room. Forty minutes to central Accra via the motorway, a world away.",
    listingType: "sale",
    propertyType: "house",
    price: 1560000,
    bedrooms: 5,
    bathrooms: 4,
    areaSqft: 3920,
    lotSqft: 217800,
    yearBuilt: 2015,
    address: "Plot 8, Reserve Road, Shai Hills",
    city: "Shai Hills",
    state: "Greater Accra",
    zip: "GD-089-1140",
    images: [px(7598375), px(8089172), px(7031879), px(6394612)],
    features: [
      "5 private acres",
      "Savanna & kopje views",
      "1,200 sq ft powered barn",
      "2024 full renovation",
      "Vaulted stone-hearth great room",
      "Spa-level primary wing",
      "Horse-ready paddock",
      "Workshop & gear loft",
      "Wildlife from every window",
      "40 min to central Accra",
    ],
    status: "available",
    featured: true,
    ...AGENTS.kofi,
  },
  {
    slug: "gulf-breeze-apartment-labone",
    title: "Gulf Breeze Apartment",
    description:
      "In the heart of Labone, this corner residence overlooks the Gulf of Guinea with wraparound glass and a 280 sq ft terrace built for sea-breeze evenings. Interiors are turnkey: porcelain plank floors, Italian cabinetry, and baths finished in travertine.\n\nThe building is full resort — two pools, seafront spa, padel courts, kids' splash park, and a residents' lounge. Walk to Labone's cafés; be at Osu's Oxford Street in five minutes.",
    listingType: "rent",
    propertyType: "apartment",
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1320,
    lotSqft: null,
    yearBuilt: 2017,
    address: "7 La Bypass, Residence 1204",
    city: "Labone",
    state: "Greater Accra",
    zip: "GA-058-6331",
    images: [px(5674684), px(8082242), px(7005291), px(6585757)],
    features: [
      "Corner gulf views",
      "280 sq ft wraparound terrace",
      "Two resort pools",
      "Seafront spa",
      "Padel & tennis courts",
      "Residents' lounge",
      "In-unit laundry",
      "Two garage spaces",
      "Pet friendly",
      "5 min to Oxford Street",
    ],
    status: "available",
    featured: true,
    ...AGENTS.nanaYaw,
  },
  {
    slug: "evernight-manor-kumasi",
    title: "Evernight Manor",
    description:
      "Evernight Manor crowns Nhyiaeso's ridge in a silhouette of charred timber and blackened steel. At dusk the house glows like a lantern above Kumasi's canopy — five levels of glass and gallery walls cascading down the hillside, served by a glass elevator.\n\nInside, a double-height living hall, imported kitchen, and 3,000-bottle glass wine cellar set the stage for entertaining. Five suites include a primary with cedar soaking tub and canopy-view shower. A 1,500 sq ft heated terrace with linear fire pit floats among the mahogany.",
    listingType: "sale",
    propertyType: "house",
    price: 3350000,
    bedrooms: 5,
    bathrooms: 5,
    areaSqft: 5150,
    lotSqft: 20800,
    yearBuilt: 2005,
    address: "29 Nhyiaeso Ridge, Kumasi",
    city: "Kumasi",
    state: "Ashanti Region",
    zip: "AK-204-9173",
    images: [px(31737859), px(8135496), px(7533852), px(8135118)],
    features: [
      "Charred-timber facade",
      "Glass elevator (5 levels)",
      "3,000-bottle wine cellar",
      "1,500 sq ft terrace",
      "Linear fire pit in the canopy",
      "Cedar soaking tub",
      "Double-height living hall",
      "Ridge & canopy views",
      "4-car garage",
      "Whole-home generator",
    ],
    status: "available",
    featured: false,
    ...AGENTS.nanaYaw,
  },
];

const artisanData: NewArtisan[] = [
  {
    name: "Kwabena Osei",
    trade: "mason",
    phone: "+233 24 118 3345",
    email: "kwabena.osei@builders.gh",
    location: "East Legon, Accra",
    years: 14,
    dayRate: 450,
    bio: "Block & brick work, foundations, and decorative stone. Led crews on 30+ East Legon builds; finishes clean, levels true.",
    ghanaCard: "GHA-714326589-2",
    passportPhoto: pxFace(30386124),
    status: "approved",
  },
  {
    name: "Yaw Darko",
    trade: "carpenter",
    phone: "+233 20 556 9021",
    email: null,
    location: "Achimota, Accra",
    years: 11,
    dayRate: 400,
    bio: "Roofing timber, fitted wardrobes, doors and odum-wood kitchens. Workshop-based with mobile installation crew.",
    ghanaCard: "GHA-582014736-5",
    passportPhoto: pxFace(7447362),
    status: "approved",
  },
  {
    name: "Emmanuel Tetteh",
    trade: "electrician",
    phone: "+233 55 209 7744",
    email: "e.tetteh@builders.gh",
    location: "Tema",
    years: 9,
    dayRate: 380,
    bio: "Full rewiring, inverter & solar hookups, ECG-certified inspections. Neat trunking, labelled boards, no shortcuts.",
    ghanaCard: "GHA-309645821-7",
    passportPhoto: pxFace(5083208),
    status: "approved",
  },
  {
    name: "Kofi Boamah",
    trade: "plumber",
    phone: "+233 26 440 1188",
    email: null,
    location: "Kumasi",
    years: 15,
    dayRate: 420,
    bio: "Pressurised systems, borehole plumbing, water heaters and bathroom fit-outs. Guarantees every joint for two years.",
    ghanaCard: "GHA-273849501-3",
    passportPhoto: pxFace(34592823),
    status: "approved",
  },
  {
    name: "Abdul Rahman Fuseini",
    trade: "tiler",
    phone: "+233 24 990 4477",
    email: "ar.fuseini@builders.gh",
    location: "Spintex, Accra",
    years: 8,
    dayRate: 350,
    bio: "Porcelain, marble and mosaic specialist. Laser-levelled floors, book-matched feature walls, flawless grout lines.",
    ghanaCard: "GHA-630192847-4",
    passportPhoto: pxFace(30496625),
    status: "approved",
  },
  {
    name: "Nii Armah Quaye",
    trade: "painter",
    phone: "+233 27 603 8812",
    email: null,
    location: "Dansoman, Accra",
    years: 12,
    dayRate: 300,
    bio: "Interior & exterior painting, textured feature walls and spray finishes. Premium weather-proof coatings for coastal homes.",
    ghanaCard: "GHA-451098276-8",
    passportPhoto: pxFace(4287126),
    status: "approved",
  },
  {
    name: "Samuel Ofori",
    trade: "welder",
    phone: "+233 54 318 2200",
    email: "s.ofori@builders.gh",
    location: "Nungua, Accra",
    years: 10,
    dayRate: 380,
    bio: "Burglar proofs, gates, stair rails and structural steel. Custom designs fabricated in-shop, installed to the millimetre.",
    ghanaCard: "GHA-817254903-6",
    passportPhoto: pxFace(6109552),
    status: "approved",
  },
  {
    name: "Peter Mensimah",
    trade: "pop",
    phone: "+233 24 701 5533",
    email: null,
    location: "Osu, Accra",
    years: 7,
    dayRate: 320,
    bio: "POP ceilings, bulkheads and cornices with integrated lighting channels. Smooth skimmed finishes ready for paint.",
    ghanaCard: "GHA-196735408-1",
    passportPhoto: pxFace(5082976),
    status: "approved",
  },
  {
    name: "Isaac Adjei",
    trade: "mason",
    phone: "+233 20 887 6641",
    email: null,
    location: "Aburi",
    years: 18,
    dayRate: 480,
    bio: "Retaining walls, borehole housings and hillside foundations across the Akuapem ridge. The mountain mason of choice.",
    ghanaCard: "GHA-204817963-9",
    passportPhoto: pxFace(15336911),
    status: "approved",
  },
  {
    name: "Grace Agyeman",
    trade: "painter",
    phone: "+233 55 129 9904",
    email: "grace.agyeman@builders.gh",
    location: "Takoradi",
    years: 6,
    dayRate: 260,
    bio: "Colour consultation, kids' room murals and crisp modern interiors. Fast, tidy and booked two weeks out.",
    ghanaCard: "GHA-573920641-0",
    passportPhoto: pxFace(9304685),
    status: "approved",
  },
  {
    name: "Daniel Kwarteng",
    trade: "electrician",
    phone: "+233 20 909 4411",
    email: null,
    location: "Madina, Accra",
    years: 6,
    dayRate: 300,
    bio: "Solar installs, inverters and full house rewiring across Adenta and Madina. ECG-certified, tidy cable work, honest quotes.",
    status: "pending",
  },
];

async function seed() {
  console.log("Seeding database…");
  await db.delete(inquiries);
  await db.delete(submissions);
  await db.delete(artisans);
  await db.delete(properties);
  await db.insert(properties).values(data);
  await db.insert(artisans).values(artisanData);

  const seedSubmissions: Omit<NewSubmission, "documents">[] = [
    {
      ownerName: "Comfort Tetteh",
      ownerPhone: "+233 24 551 7788",
      ownerEmail: "comfort.tetteh@example.com",
      ghanaCard: "GHA-348771205-6",
      propertyType: "house",
      address: "24 Palm Springs Close",
      city: "Dzorwulu",
      region: "Greater Accra",
      bedrooms: 5,
      bathrooms: 4,
      areaSqft: 3400,
      askingPrice: 2250000,
      description:
        "A five-bedroom family house in Dzorwulu on a walled corner plot — boys' quarters, standby generator, borehole, and a mature garden. Family relocating to Takoradi, so a motivated, documents-ready sale.",
      status: "pending",
    },
    {
      ownerName: "Kwesi Amankwah",
      ownerPhone: "+233 20 448 9012",
      ownerEmail: null,
      ghanaCard: "GHA-902514836-1",
      propertyType: "townhouse",
      address: "8 Ridge Court, Roman Ridge",
      city: "Roman Ridge",
      region: "Greater Accra",
      bedrooms: 4,
      bathrooms: 4,
      areaSqft: 2650,
      askingPrice: 1750000,
      description:
        "Corner townhouse in a gated eight-unit court — solar water heaters, allocated parking for three, and a communal pool. Title is freehold and registered; site plan stamped by a licensed surveyor.",
      status: "reviewing",
    },
  ];

  for (let i = 0; i < seedSubmissions.length; i++) {
    const s = seedSubmissions[i];
    const documents = await seedDocuments(i + 1, s.ownerName);
    await db.insert(submissions).values({ ...s, documents });
  }

  console.log(
    `Inserted ${data.length} properties, ${artisanData.length} artisans, and ${seedSubmissions.length} sell requests.`,
  );
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
